apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-scripts
  namespace: enterprise-security
data:
  init.sql: |
    CREATE USER user_service WITH PASSWORD 'user-service-demo-pw';
    CREATE DATABASE user_service OWNER user_service;

    CREATE USER order_service WITH PASSWORD 'order-service-demo-pw';
    CREATE DATABASE order_service OWNER order_service;

    CREATE USER admin_service WITH PASSWORD 'admin-service-demo-pw';
    CREATE DATABASE admin_service OWNER admin_service;

    CREATE USER keycloak WITH PASSWORD 'keycloak-demo-pw';
    CREATE DATABASE keycloak OWNER keycloak;
